SAS OFF.

SET tgtHeading to MOD(ROUND(360 - SHIP:BEARING),360).

LOCK STEERING TO HEADING(tgtHeading,90).
LOCK THROTTLE TO 1.

WAIT 30.
//WAIT UNTIL ETA:APOAPSIS = 0.
LOCK STEERING TO PROGRADE.

WAIT UNTIL SHIP:ORBIT:HASNEXTPATCH.
LOCK THROTTLE TO 1 - ((40000 / SHIP:ORBIT:NEXTPATCH:PERIAPSIS)^2).
WAIT UNTIL SHIP:ORBIT:NEXTPATCH:PERIAPSIS < 40000.

UNLOCK THROTTLE.
UNLOCK STEERING.
SET SHIP:CONTROL:PILOTMAINTHROTTLE TO 0.
